name 'casperjs'
maintainer 'Nick Lopez'
maintainer_email 'nlopez@gmail.com'
license 'all_rights'
description 'Installs/Configures CasperJS'
long_description 'Installs/Configures CasperJS'
version '0.1.1'

depends 'phantomjs'
depends 'ark'
