name 'casperjs'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures casperjs'
long_description 'Installs/Configures casperjs'
version '0.1.0'
